---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
script: bundle exec rake spec
env:
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
matrix:
  allow_failures:
    - env: PUPPET_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
